### ISSUE TITLE
Sonarr/Radarr integration

### ISSUE THREAD

**Issue by balgerion** [kennethsible/mkvpriority#2]
I`m back! ;)  sry

im testing sonarr integration and there is small problem - maybe its my mistake. I tried to run it at diffrent configurations but all of them failed:

ver1: 

so this is my docker compose 

```
  mkvpriority:
    image: ghcr.io/kennethsible/mkvpriority:latest
    container_name: arr-suite-mkvpriority-Anime
    environment:
      - WEBHOOK_RECEIVER=true
      - MKVPRIORITY_ARGS=
    volumes:
      - /mnt/Balgeriada1/Media/anime:/anime
      - /mnt/Balgeriada1/docker/app/arr-suite/configs/mkvpriority-anime/archive.db:/app/archive.db  
      - /mnt/Balgeriada1/docker/app/arr-suite/configs/mkvpriority-anime/config.toml:/app/config.toml  
    restart: unless-stopped
```

Script:
```
#!/bin/bash

CONTAINER_NAME='arr-suite-mkvpriority-Anime' # <-- change if you use a different name
FILE_PATH="${sonarr_episodefile_path:-${radarr_moviefile_path}}"

[ -z "$FILE_PATH" ] && exit 0

curl -sS -X POST "http://${CONTAINER_NAME}:8080/process" \
     -H "Content-Type: application/json" \
     -d '{"file_path": "'"$FILE_PATH"'"}'
```

added to Sonarr and tested :

![Image](https://github.com/user-attachments/assets/7098a7a8-6da1-44c1-b85e-bd36226e1d8c)

all good , but  container is doing nothing on import:

![Image](https://github.com/user-attachments/assets/ce7c46ed-9a0f-4352-8ca0-602d6caa24e7)

ver 2:
Ok i have quite big stack ARR so maybe this is port problem - lest try to use diffrent and expose it outside stack

compose:
```
  mkvpriority:
    image: ghcr.io/kennethsible/mkvpriority:latest
    container_name: arr-suite-mkvpriority-Anime
    environment:
      - WEBHOOK_RECEIVER=true
      - MKVPRIORITY_ARGS=
    volumes:
      - /mnt/Balgeriada1/Media/anime:/anime
      - /mnt/Balgeriada1/docker/app/arr-suite/configs/mkvpriority-anime/archive.db:/app/archive.db  
      - /mnt/Balgeriada1/docker/app/arr-suite/configs/mkvpriority-anime/config.toml:/app/config.toml  
    restart: unless-stopped
    expose:
      - 7779/tcp 
    ports:
      - 7779:8080/tcp 
```

script 

```
#!/bin/bash

CONTAINER_NAME='192.168.1.21' # <-- change if you use a different name
FILE_PATH="${sonarr_episodefile_path:-${radarr_moviefile_path}}"

[ -z "$FILE_PATH" ] && exit 0

curl -sS -X POST "http://${CONTAINER_NAME}:7779/process" \
     -H "Content-Type: application/json" \
     -d '{"file_path": "'"$FILE_PATH"'"}'
```
tested sonarr and via browser - working. 
same effect on import - nothing

![Image](https://github.com/user-attachments/assets/9298b9dd-8cf7-4407-8b1f-faf74b031357)

I have Ruddarr configured for testing to check if there's a problem with my webhooks, but it's working without any issues (I'm receiving notifications).

![Image](https://github.com/user-attachments/assets/a32f9cef-4e2d-4e7a-b2cd-d35701aa0ddf)
