### ISSUE TITLE
How do you run it as a cronjob in Docker when there is no crontab?

### ISSUE THREAD

**Issue by nothing2obvi** [kennethsible/mkvpriority#5]
Or are there plans to allow users to input a cron schedule as an environment variable?

**Comment by kennethsible** [comment]
I considered adding a cron schedule as an environment variable, but I decided against it to avoid conflicting behavior when using `docker compose`. I added compose support for the webhook receiver, but a cron schedule is used for batch processing. Is there not a crontab alternative that you could use with `docker run` for task scheduling on your OS?

**Comment by nothing2obvi** [comment]
Thanks for your response. I tend to run things in Portainer, which uses `docker compose` templates, but I could work with `docker run`. I was just curious if there was something I was missing. Just my opinion of course, but it seems like since many users (including myself) may choose to run mkvpriority on a schedule (e.g. users not using Sonarr/Radarr), some sort of cron feature should be considered.

**Comment by kennethsible** [comment]
I see your point! I didn't consider strictly using stack managers such as Portainer or Dockge for batch processing. I'll look into adding a native cron schedule soon, but in the meantime, I found a workaround using a Docker job scheduler called [Ofelia](https://github.com/mcuadros/ofelia).

```yaml
services:
  ofelia:
    image: mcuadros/ofelia
    depends_on:
      - mkvpriority
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mkvpriority:
    image: ghcr.io/kennethsible/mkvpriority
    container_name: mkvpriority
    user: ${PUID}:${PGID}
    environment:
      WEBHOOK_RECEIVER: true
    volumes:
      - "${PWD}/media:/media"
      - "${PWD}/config:/config"
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.mkvpriority.schedule: "0 0 1 * * *"
      ofelia.job-exec.mkvpriority.command: "mkvpriority -a /config/archive.db -n /media"
```

**Comment by kennethsible** [comment]
@nothing2obvi I added a built-in cron scheduler (69b2626343afa707cff50a1df2ffa9cdcaac47c0). If you want to test it, add the `:develop` tag to the Docker image.

```yaml
mkvpriority:
  image: ghcr.io/kennethsible/mkvpriority
  container_name: mkvpriority
  user: ${PUID}:${PGID}
  environment:
    TZ: "America/New_York"
    CRON_SCHEDULE: "0 5 * * *"
    MKVPRIORITY_ARGS: -a /config/archive.db /media
  volumes:
    - /path/to/media:/media
    - /path/to/mkvpriority/config:/config
  restart: unless-stopped
```
